### ISSUE TITLE
Unenrolling via sh1mmer as well as downgrading are impossible in versions after chromeOS 111

### ISSUE THREAD

**Issue by ItsTact** [CoolElectronics/sh1mmer.me#57] opened 2023-05-04 03:41 UTC
i don't want to spend 20 more hours trying to get chrome 112 to downgrade with various bash commands that don't work if someone else has found a solution

**Comment by amelia-bartlett** [comment] 2023-05-04 09:01
you dont need bash commands to _downgrade_, you just need a recovery usb.  You need shell commands to block fw upgrade.
IMPORTANT: DO NOT RUN THE SH1MMER BUILD TOOL ON THE RECOVERY USB, FLASH IT DIRECTLY

You can use fakemurk to block updates automatically, and make your chromebook appear enrolled still.

If you want to sign in with a home account instead (i.e. you don't want to use fakemurk):
After downgrading,  you can use sh1mmer mostly as normal.  Some stuff doesnt work (since 112 patched the security chip firmware, and you cant downgrade that), but you can still unenroll.  Once unenrolled, get developer mode with the standard procedure (the one for chromebooks that are not enterprise-enrolled, you cannot do it from sh1mmer with the security chip fw update).  Once you get back to Chrome OS, do not connect to a network, but switch to virtual terminal 2.  Disable rootfs verification, then reboot.  Get back to vt2.  Replace the unit file for the update service with a dummy one that does nothing.  Reboot again, switch to vt2 again, and verify the change to the unit file persisted.  If it did, you can now connect to a network and set up Chrome OS.

This is basically what I did, except I used sh1mmer before the patch, so I cannot verify whether you can e.g. get vt2 on the sign in screen.  I can confirm replacing the update service unit file with a dummy one (e.g. prepend a hashtag to every line to make it all comments) does indeed prevent updates from occurring, at least on 110.

**Comment by ItsTact** [comment] 2023-05-04 11:42
i already succeeded in using sh1mmer on 108, but me being dumb updated to 112 to use linux, and then i couldn't downgrade to do anything, as all of the sh1mmer build utilities lead to a line 73 error.

are you sure what you're saying applies here?

**Comment by amelia-bartlett** [comment] 2023-05-04 11:44
> i already succeeded in using sh1mmer on 108, but me being dumb updated to 112 to use linux, and then i couldn't downgrade to do anything, as all of the sh1mmer build utilities lead to a line 73 error.
> 
> are you sure what you're saying applies here?

huh let me look at that to see if there is anything obvious

Are you using the web builder or the local one?

**Comment by amelia-bartlett** [comment] 2023-05-04 11:45
Line 73 of `wax.sh` looks like this:
```echo "Injecting payload"```
are you using `wax_macos.sh` by any chance?

(on wax_macos.sh it is a copy operation, which could potentially fail)

**Comment by ItsTact** [comment] 2023-05-04 11:46
no
i used the web builder but i am 100% it was working before i updated to 112
downgrading leads me to google's "this is not a valid thing"

**Comment by ItsTact** [comment] 2023-05-04 11:47
Message is:
line 73: read: THERE WAS AN ERROR! The utility likely did not work. Press return to continue.

**Comment by amelia-bartlett** [comment] 2023-05-04 11:47
> no i used the web builder but i am 100% it was working before i updated to 112 downgrading leads me to google's "this is not a valid thing" it might have been line 71 or something but it's where it says the utility didn't work, let me find a ss

huh, not sure how the web builder works (i built locally)

**Comment by amelia-bartlett** [comment] 2023-05-04 11:47
> Message is: line 73: read: THERE WAS AN ERROR! The utility likely did not work. Press return to continue.

What happens if you, well, press return to continue?

**Comment by amelia-bartlett** [comment] 2023-05-04 11:48
wait

I think I recognise that error

**Comment by ItsTact** [comment] 2023-05-04 11:48
returns to the menu and then upon restart the device is enrolled again and i can't log in to anything but a school account

**Comment by ItsTact** [comment] 2023-05-04 11:50
i am pretty sure this is patched i just want Mr. Cool Electronics here to post part 4 on their blog to see if they have a solution to this instead of me trying and failing to inject code

**Comment by amelia-bartlett** [comment] 2023-05-04 11:52
> returns to the menu and then upon restart the device is enrolled again and i can't log in to anything but a school account

which option did you select in the menu?

**Comment by ItsTact** [comment] 2023-05-04 11:53
GBB, unenroll, and unblock dev mode had the problems i think
i can try again but that takes another couple minutes

**Comment by amelia-bartlett** [comment] 2023-05-04 11:54
> GBB, unenroll, and unblock dev mode had the problems i think i can try again but that takes another couple minutes

unblock dev mode is known to be broken at the moment

I *think* you just need GBB and unenroll to work to be able to unenroll (there is a race condition you can abuse from there to get dev mode)

**Comment by ItsTact** [comment] 2023-05-04 11:55
what's the "race condition"

**Comment by amelia-bartlett** [comment] 2023-05-04 11:58
> what's the "race condition"

its not really relevant here, its basically how you can get dev mode even with the patch to the security chip (basically there is a brief window in which you can take ownership of it)

**Comment by amelia-bartlett** [comment] 2023-05-04 12:02
> GBB, unenroll, and unblock dev mode had the problems i think i can try again but that takes another couple minutes

OK, I have little to no clue why they are going wrong (apart from the fact the unenroll option runs the enable dev mode option as well, which is probably why you get an error with it)

I am going to find out where the gbb flag setting script is, to see if I can figure out what is wrong with it

(by the way, posting error messages verbatim really helps with figuring out what the heck happened)

(also, have you built a new shim and tested that since you first unenrolled?  there might have been an update that works around this)

**Comment by ItsTact** [comment] 2023-05-04 12:04
i have not done that, i will check later today.
also i only have that one error message i got above
thanks for the help, i'll get back to this

**Comment by amelia-bartlett** [comment] 2023-05-04 12:05
oh huh the gbb flag setting script looks like it is part of the stock shims

it looks like the gbb flags utility in sh1mmer just tries to clear all of them

**Comment by amelia-bartlett** [comment] 2023-05-04 12:06
Also, have you rolled back your chromeOS version?

chromeOS always checks enrollment starting from version 111 (before, it would only check if the relevant vpd flag was set)

**Comment by ItsTact** [comment] 2023-05-04 12:07
i thought i mentioned i'm on version 112

**Comment by amelia-bartlett** [comment] 2023-05-04 12:07
> i thought i mentioned i'm on version 112

ah yeah that would be it my bad

**Comment by amelia-bartlett** [comment] 2023-05-04 12:07
> > i thought i mentioned i'm on version 112
> 
> ah yeah that would be it my bad

you did mention it, I should have made it more clear you need to downgrade

**Comment by amelia-bartlett** [comment] 2023-05-04 12:08
https://chrome100.dev/ should have a recovery image for your board

**Comment by ItsTact** [comment] 2023-05-04 12:08
the thing is, i can't, so i guess that's it

**Comment by amelia-bartlett** [comment] 2023-05-04 12:08
> the thing is, i can't, so i guess that's it

what board do you have?

**Comment by ItsTact** [comment] 2023-05-04 12:10
octopus
at version 112 when i try to downgrade to 110 it throws "You are using an outdated ChromeOS image"

**Comment by amelia-bartlett** [comment] 2023-05-04 12:10
> octopus at version 112 when i try to downgrade to 110 it throws "You are using an outdated ChromeOS image"

dangit

**Comment by ItsTact** [comment] 2023-05-04 12:12
![image](https://user-images.githubusercontent.com/69988786/236200201-2166803b-2c22-4f24-a4f2-d2effcbfeeba.png)
precisely why i am asking when a part 4 is coming

**Comment by amelia-bartlett** [comment] 2023-05-04 12:12
ah yeah

there *might* be a way to do it, but its a long shot

**Comment by ItsTact** [comment] 2023-05-04 12:13
go on

**Comment by amelia-bartlett** [comment] 2023-05-04 12:13
So, basically, one of the GBB flags is `GBB_FLAG_DISABLE_FW_ROLLBACK_CHECK`

You could potentially set it from within sh1mmer

**Comment by amelia-bartlett** [comment] 2023-05-04 12:13
I think there is an option to get a shell directly in sh1mmer

**Comment by ItsTact** [comment] 2023-05-04 12:14
yes there is i will try that

**Comment by amelia-bartlett** [comment] 2023-05-04 12:14
I think you would have to run `/usr/share/vboot/bin/set_gbb_flags.sh 0x00000020`

**Comment by amelia-bartlett** [comment] 2023-05-04 12:18
> I think you would have to run `/usr/share/vboot/bin/set_gbb_flags.sh 0x00000020`

after running it, see if you can downgrade

if not, then I don't know how to proceed (other than pulling out the motherboard and editing the data on the SPI flash with an external programmer, which I do not really know how to do)

**Comment by ItsTact** [comment] 2023-05-04 15:19
i misremembered, gbb is enabled but unroll and unblock dev is not, i tried downgrading in dev mode and it worked, with a message saying that it could downgrade cause it was in dev mode, but it then sent me to the ChromeOS is missing or damaged screen, and it would not load chrome 110 no matter what buttons i pressed

**Comment by amelia-bartlett** [comment] 2023-05-04 15:23
> i misremembered, gbb is enabled but unroll and unblock dev is not, i tried downgrading in dev mode and it worked, with a message saying that it could downgrade cause it was in dev mode, but it then sent me to the ChromeOS is missing or damaged screen, and it would not load chrome 110 no matter what buttons i pressed

(hopefully this doesn't get posted repeatedly or something)

what happens if you hit CTRL+D or wait 30 seconds without doing anything?

**Comment by ItsTact** [comment] 2023-05-04 15:24
ctrl+d doesn't work and waiting doesn't do anything either

**Comment by ItsTact** [comment] 2023-05-04 15:25
pressing tab brings up recovery_reason: 0x5b / 0x5b No bootable kernel found on disk
i think then it's probably my downgraded usb's problem, but i'll have to wait until i get home to fix that

**Comment by amelia-bartlett** [comment] 2023-05-04 15:26
i thought as much, it seems like it isnt finding chromeos

**Comment by amelia-bartlett** [comment] 2023-05-04 15:27
it might be something to do with firmware management parameters - have you booted sh1mmer after downgrading?

either that, or its a corrupt/badly flashed recovery image

**Comment by ItsTact** [comment] 2023-05-04 15:28
i sh1mmered it and then made it downgrade
i just stuck my sh1mmer usb in and it says the device you inserted does not contain chrome os
i've tried recovering twice to no avail
playing around with it more at the moment

**Comment by ItsTact** [comment] 2023-05-04 15:32
ok i'm pretty sure it's the recovery image, because sh1mmer still works
really hoping my chromebook is not bricked

**Comment by ItsTact** [comment] 2023-05-04 23:26
ok after a bit more playing around, here's the official "case status" for what happens on chromebooks loaded with version 112.0.5615.134, i'm on octopus specifically
1. Sh1mmer does work and flash, but trying to unenroll or unblock dev mode leads to `line 73: read: THERE WAS AN ERROR! The utility likely did not work. Press return to continue.` Everything else works.
2. When trying to downgrade by flashing a recovery image from Chromium Dash or [chrome100.dev](url), it will first verify if it is valid, and if not in developer mode, it will refuse to work
3. If flashing the recovery image in developer mode, it will succeed in verifying it but will warn the user that the only reason they can do this is because developer mode is on. After this happens, the chromebook will prompt the recovery usb to be taken out, and upon restarting, will throw "ChromeOS is missing or damaged". Pressing Ctrl+D or the Esc+Refresh+Power salute will not stop this from happening, the error displayed by pressing tab is "recovery_reason: 0x5b / 0x5b No bootable kernel found on disk". the only way to unbrick the chromebook is to load the image file through the chromebook brand dropdown in the chromebook recovery extension (example: my chromebook is ASUS C204), and only then will it boot up correctly. Still nothing will work because the version pulled is still 112.

**Comment by ghost** [comment] 2023-05-05 12:31
im not reading all this lol
if yall wanna have a conversation can you take it elsewhere, you're taking up space inside an issue
try going into the tn discord
someone close this lol

**Comment by TheMemeSniper** [comment] 2023-05-05 12:33
idc if y'all continue as long as you wrap it up eventually

**Comment by amelia-bartlett** [comment] 2023-05-06 09:32
> ok after a bit more playing around, here's the official "cast status" for what happens on chromebooks loaded with version 112.0.5615.134, i'm on octopus specifically
> 
>     1. Sh1mmer does work and flash, but trying to unenroll or unblock dev mode leads to `line 73: read: THERE WAS AN ERROR! The utility likely did not work. Press return to continue.` Everything else works.
> 
>     2. When trying to downgrade by flashing a recovery image from Chromium Dash or [chrome100.dev](url), it will first verify if it is valid, and if not in developer mode, it will refuse to work
> 
>     3. If flashing the recovery image in developer mode, it will succeed in verifying it but will warn the user that the only reason they can do this is because developer mode is on. After this happens, the chromebook will prompt the recovery usb to be taken out, and upon restarting, will throw "ChromeOS is missing or damaged". Pressing Ctrl+D or the Esc+Refresh+Power salute will not stop this from happening, the error displayed by pressing tab is "recovery_reason: 0x5b / 0x5b No bootable kernel found on disk". the only way to unbrick the chromebook is to load the image file through the chromebook brand dropdown in the chromebook recovery extension (example: my chromebook is ASUS C204), and only then will it boot up correctly. Still nothing will work because the version pulled is still 112.

I think you can load older images manually through the chromebook recovery extension, but im not sure

it seems your older image is bad (which is why you cannot flash it outside of dev mode, and it leaves you without a valid kernel) - this could either be due to it getting corrupted while downloading, it being corrupted on the website (maybe try a different one that is 110 or below?) or it getting corrupted during flashing.

Also, there are two variants of the board ID: one is used by the RMA shim (can't remember the exact name of it) and the other is the customisation ID, which should display somewhere in the recovery.  I think you want the customisation ID for selecting a recovery image, and sometimes they are different (e.g. volteer board/collis customisation ID)

**Comment by velzie** [comment] 2023-05-07 16:32
Soon:tm:

downgrading, as well as all forms are unenrollment are patched by google in 112.
there will be a workaround when part 4 drops which will be in like a week or 2 idk

I'm leaving this open for now as a representation of the current state of the project

**Comment by ItsTact** [comment] 2023-05-07 17:17
btw i did manage to downgrade to 108 LTS (108.0.5359.230) last night but as the blog says, it was patched in April; 108 LTC 108.0.5359.221) will still refuse to boot on mine

**Comment by ghost** [comment] 2023-05-09 12:27
CoolElectronics if you want to make the state of the project more obvious, why don't you put it in the README lol

**Comment by misterfonka** [comment] 2023-05-10 02:50
Downgrade using Balena Etcher, download a recovery image from chrome100.dev, flash it and it will work.

**Comment by ItsTact** [comment] 2023-05-10 12:38
> Downgrade using Balena Etcher, download a recovery image from chrome100.dev, flash it and it will work.

No it will not.

**Comment by HAHALOSAH** [comment] 2023-05-10 22:36
(ONLY WORKS IF YOUR CHROMEBOOK HAS NEVER UPDATED TO 112 BEFORE, NO LONGER FUNCTIONAL)
Alright, so this is what worked for me
1. Use sh1mmer and fix GBB
2. Downgrade to older ChromeOS with an image from https://chrome100.dev
3. Go back to sh1mmer, fix GBB & deprovision, then disable updates
4. Enable OS verification
5. Go through chromebook setup screen until it asks who is using this, then you can enable developer mode if you want

**Comment by misterfonka** [comment] 2023-05-15 00:29
> Downgrade using Balena Etcher, download a recovery image from chrome100.dev, flash it and it will work.

It will only work in v112

**Comment by ghost** [comment] 2023-05-15 19:50
dead chat :skull:

**Comment by TheMemeSniper** [comment] 2023-05-15 20:02
shut the fuck up

**Comment by soopmestr7** [comment] 2023-05-16 23:42
> > what's the "race condition"
> 
> its not really relevant here, its basically how you can get dev mode even with the patch to the security chip (basically there is a brief window in which you can take ownership of it)

how do you do that?

**Comment by amelia-bartlett** [comment] 2023-05-17 09:51
> > > what's the "race condition"
> > 
> > 
> > its not really relevant here, its basically how you can get dev mode even with the patch to the security chip (basically there is a brief window in which you can take ownership of it)
> 
> how do you do that?

fakemurk sets it up automatically, but to use fakemurk you need to be able to use sh1mmer

you could probably take a look at the fakemurk code and rip that part out, but idk which partition of the shim you would need to put it in (if its the kernel partition, you cant, but if its the rootfs, you probably can if you set everything else up correctly)

**Comment by velzie** [comment] 2023-05-17 11:23
112 blocks modification of certain tpm values during _recovery_ boot mode specifically. no commands will help. there are several methods of unenrolling past 112 if you're willing to take write protection off, which requires taking off the back of your chromebook (for example setting gbb flags)
if that's out of your scope, you'll have to wait for our semi-patch-bypass to release in a stable state

**Comment by soopmestr7** [comment] 2023-05-19 04:59
> i don't want to spend 20 more hours trying to get chrome 112 to downgrade with various bash commands that don't work if someone else has found a solution

take out the battery, run the unenroll script and you should see an error, go to bash and type "/usr/share/vboot/bin/set_gbb_flags.sh 0x8090", then you should be able to use dev mode and downgrade because it works in dev mode and sign in and update it afterwards. Hope this helps.

**Comment by ItsTact** [comment] 2023-05-19 12:35
> > i don't want to spend 20 more hours trying to get chrome 112 to downgrade with various bash commands that don't work if someone else has found a solution
> 
> take out the battery, run the unenroll script and you should see an error, go to bash and type "/usr/share/vboot/bin/set_gbb_flags.sh 0x8090", then you should be able to use dev mode and downgrade because it works in dev mode and sign in and update it afterwards. Hope this helps.

The problem with this approach is that upon reaching the signing in page the chromebook errors with something something time-lock management something, because the chromebook realizes it's not supposed to be in dev mode but it is. the bottom left sign in with personal account button doesn't work upon clicking

**Comment by velzie** [comment] 2023-05-19 12:37
that's not a problem with the method it's an occasional odd chromebook bug that is fixed by powerwashing or recovering

**Comment by ItsTact** [comment] 2023-05-19 12:39
but like i tried it about 10 times...

**Comment by velzie** [comment] 2023-05-19 13:00
it's not a problem with either sh1mmer nor the gbb method, go somewhere else for your issues

**Comment by trevorwatkins1129** [comment] 2023-05-19 13:21
Hmm. I'm on Dedede with ChromeOS v112.0.5615.134, and it works fine for me.

**Comment by Dr-Bob-isTheBestDoctor** [comment] 2023-05-19 15:43
Maybe a stupid question but could you just replace the version of an older recovery image and just trick the chromebook check?

**Comment by ItsTact** [comment] 2023-05-21 15:49
sh1mmer website was updated with instructions, if they don't work then cope harder

**Comment by velzie** [comment] 2023-05-21 15:55
(reopening as full instructions haven't been added yet, will close when we finish with adding the alternative methods)

**Comment by velzie** [comment] 2023-05-25 03:10
fixed by https://fog.gay

**Closed as completed by velzie** 2023-05-25 03:10 UTC

**Comment by onsomlem** [comment] 2023-06-15 17:44
> no i used the web builder but i am 100% it was working before i updated to 112 downgrading leads me to google's "this is not a valid thing"

Try doing this:
Hold the esc + refresh/f3 + powerbutton,
for a little or just press it 🤷. Once your screen stops moving and says insert recovery media just press: 
ctrl + d*, 
(*the letter d on your keyboard guys) and then: enter (to continue how it says on your screen right now if you're following)
when your screen says " OS verification is off **DO NOT PRESS SPACE**
instead press: esc + refresh/f3 + powerbutton and then plug your recovery media in once the screen says to. it should not complain about your recovery media not being up to date . If it does not work my knowledge is now obsolete and i quit cuz i put my life force into this 💀

**Comment by ben10101010** [comment] 2023-07-16 20:15
Or, you could follow the intructions on the sh1mmer website, which tells you how to turn off WP, then unenroll your chromebook. Didn’t work for me though, I might have to get a special cable to disable it.

**Comment by MunyDev** [comment] 2023-12-21 16:28
Cryptosmite

**Comment by inLnx** [comment] 2024-08-23 23:00
yall still here?

**Comment by seoProductions** [comment] 2025-04-08 21:57
bump, any one still here?

> yall still here?
